version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_DSN: "postgres://user:password@db:5432/news_db?sslmode=disable"
    volumes:
      - app_data:/app

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
