// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type News struct {
	ID      int32
	Title   string
	Content string
}

type Newscategory struct {
	Newsid     int32
	Categoryid int32
}
