// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: news.sql

package db

import (
	"context"
)

const createNews = `-- name: CreateNews :exec
INSERT INTO News (Title, Content) VALUES ($1, $2)
`

type CreateNewsParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) error {
	_, err := q.db.Exec(ctx, createNews, arg.Title, arg.Content)
	return err
}

const getNewsById = `-- name: GetNewsById :one
SELECT id, title, content FROM News WHERE Id = $1
`

func (q *Queries) GetNewsById(ctx context.Context, id int32) (News, error) {
	row := q.db.QueryRow(ctx, getNewsById, id)
	var i News
	err := row.Scan(&i.ID, &i.Title, &i.Content)
	return i, err
}
